# Generated by Django 5.2 on 2025-04-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_flower_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('joining_date', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_delivery', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('delivered_datetime', models.DateTimeField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowerapp.order')),
                ('delivery_staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowerapp.delivery_staff')),
            ],
        ),
    ]
