# Generated by Django 5.2 on 2025-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0003_delivery_staff_alter_flower_description_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AddField(
            model_name='flower',
            name='isAvail',
            field=models.BooleanField(default=True),
        ),
    ]
